language: python
python:
  - "3.6"      # current default Python on Travis CI

services:
  - docker
# command to install dependencies
install:
  - pip install -r ../requirements.txt

before_install: 
  - cd HavocOS_Web 

# command to run tests
script:
  - cd HavocOS_Web/ && python manage.py test && cd ..

deploy:
  cleanup: false
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
