# Generated by Django 3.0.2 on 2020-04-25 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('Desc', models.TextField()),
                ('Gitlink', models.CharField(blank=True, max_length=500)),
                ('Paylink', models.CharField(blank=True, max_length=500)),
                ('Tellink', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Codename', models.CharField(max_length=100)),
                ('Dlink', models.CharField(max_length=500)),
                ('Maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='havochome.Developer')),
            ],
        ),
    ]
