# Generated by Django 3.0.2 on 2020-04-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havochome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='Imlink',
            field=models.CharField(default="{{ static 'havochome/assets/profile.jpeg' }}", max_length=500),
        ),
        migrations.AddField(
            model_name='developer',
            name='Xdalink',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='device',
            name='Sflink',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
