# Generated by Django 3.0.2 on 2020-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havochome', '0003_auto_20200425_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Dlink',
        ),
        migrations.RemoveField(
            model_name='device',
            name='Name',
        ),
        migrations.AddField(
            model_name='device',
            name='Xdalink',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
