# Generated by Django 3.0.2 on 2020-04-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havochome', '0004_auto_20200425_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='Imlink',
            field=models.CharField(default='/static/havochome/assets/profile.jpeg', max_length=500),
        ),
    ]
